apiVersion: v1
kind: ConfigMap
metadata:
  name: zehraguard-config
  namespace: zehraguard
data:
  POSTGRES_DB: "zehraguard"
  POSTGRES_USER: "zehraguard"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  INFLUXDB_URL: "http://influxdb-service:8086"
  INFLUXDB_ORG: "zehraguard"
  INFLUXDB_BUCKET: "behavioral_data"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "zehraguard"
  DEBUG: "false"
  ENVIRONMENT: "production"
