apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: zehraguard
type: Opaque
data:
  username: emVocmFndWFyZA== # zehraguard
  password: c2VjdXJlX3Bhc3N3b3JkXzEyMw== # secure_password_123
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: zehraguard
type: Opaque
data:
  password: cmVkaXNfcGFzc3dvcmRfMTIz # redis_password_123
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
  namespace: zehraguard
type: Opaque
data:
  username: YWRtaW4= # admin
  password: YWRtaW5fcGFzc3dvcmRfMTIz # admin_password_123
  token: emVocmFndWFyZC1zdXBlci1zZWNyZXQtYXV0aC10b2tlbg== # zehraguard-super-secret-auth-token
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: zehraguard
type: Opaque
data:
  username: emVocmFndWFyZA== # zehraguard
  password: cmFiYml0bXFfcGFzc3dvcmRfMTIz # rabbitmq_password_123
---
apiVersion: v1
kind: Secret
metadata:
  name: zehraguard-secret
  namespace: zehraguard
type: Opaque
data:
  secret-key: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u # your-super-secret-key-change-in-production
